[tool.poetry]
name = "demo"
version = "0.1.0"
description = "Simulate Digital Rail demo"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
railway-route-generator = {git = "https://github.com/simulate-digital-rail/railway-route-generator"}
orm-planpro-converter = {git = "https://github.com/simulate-digital-rail/orm-importer"}
planpro-exporter = {git = "https://github.com/simulate-digital-rail/planpro-exporter"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
